# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dist_calc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dist_calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64ist_calc.proto\x12\nmiddleware\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\";\n\x0fWorkloadRequest\x12\x12\n\noperations\x18\x01 \x01(\x05\x12\x14\n\x0cpayload_size\x18\x02 \x01(\x05\"#\n\x10WorkloadResponse\x12\x0f\n\x07time_ms\x18\x01 \x01(\x01\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x01\"1\n\x0f\x41verageResponse\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x01\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\xda\x01\n\x15\x44istributedCalculator\x12\x36\n\x03Sum\x12\x16.middleware.SumRequest\x1a\x17.middleware.SumResponse\x12\x45\n\x08Workload\x12\x1b.middleware.WorkloadRequest\x1a\x1c.middleware.WorkloadResponse\x12\x42\n\rStreamAverage\x12\x12.middleware.Number\x1a\x1b.middleware.AverageResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dist_calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMREQUEST']._serialized_start=31
  _globals['_SUMREQUEST']._serialized_end=65
  _globals['_SUMRESPONSE']._serialized_start=67
  _globals['_SUMRESPONSE']._serialized_end=96
  _globals['_WORKLOADREQUEST']._serialized_start=98
  _globals['_WORKLOADREQUEST']._serialized_end=157
  _globals['_WORKLOADRESPONSE']._serialized_start=159
  _globals['_WORKLOADRESPONSE']._serialized_end=194
  _globals['_NUMBER']._serialized_start=196
  _globals['_NUMBER']._serialized_end=219
  _globals['_AVERAGERESPONSE']._serialized_start=221
  _globals['_AVERAGERESPONSE']._serialized_end=270
  _globals['_DISTRIBUTEDCALCULATOR']._serialized_start=273
  _globals['_DISTRIBUTEDCALCULATOR']._serialized_end=491
# @@protoc_insertion_point(module_scope)
