# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dist_calc_pb2 as dist__calc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dist_calc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DistributedCalculatorStub(object):
    """Serviço principal de processamento distribuído
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sum = channel.unary_unary(
                '/middleware.DistributedCalculator/Sum',
                request_serializer=dist__calc__pb2.SumRequest.SerializeToString,
                response_deserializer=dist__calc__pb2.SumResponse.FromString,
                _registered_method=True)
        self.Workload = channel.unary_unary(
                '/middleware.DistributedCalculator/Workload',
                request_serializer=dist__calc__pb2.WorkloadRequest.SerializeToString,
                response_deserializer=dist__calc__pb2.WorkloadResponse.FromString,
                _registered_method=True)
        self.StreamAverage = channel.stream_unary(
                '/middleware.DistributedCalculator/StreamAverage',
                request_serializer=dist__calc__pb2.Number.SerializeToString,
                response_deserializer=dist__calc__pb2.AverageResponse.FromString,
                _registered_method=True)


class DistributedCalculatorServicer(object):
    """Serviço principal de processamento distribuído
    """

    def Sum(self, request, context):
        """RPC simples: soma dois números
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Workload(self, request, context):
        """RPC com carga: servidor executa N operações e devolve o tempo gasto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAverage(self, request_iterator, context):
        """Streaming: cliente envia vários números, servidor calcula a média
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sum': grpc.unary_unary_rpc_method_handler(
                    servicer.Sum,
                    request_deserializer=dist__calc__pb2.SumRequest.FromString,
                    response_serializer=dist__calc__pb2.SumResponse.SerializeToString,
            ),
            'Workload': grpc.unary_unary_rpc_method_handler(
                    servicer.Workload,
                    request_deserializer=dist__calc__pb2.WorkloadRequest.FromString,
                    response_serializer=dist__calc__pb2.WorkloadResponse.SerializeToString,
            ),
            'StreamAverage': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAverage,
                    request_deserializer=dist__calc__pb2.Number.FromString,
                    response_serializer=dist__calc__pb2.AverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'middleware.DistributedCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('middleware.DistributedCalculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DistributedCalculator(object):
    """Serviço principal de processamento distribuído
    """

    @staticmethod
    def Sum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/middleware.DistributedCalculator/Sum',
            dist__calc__pb2.SumRequest.SerializeToString,
            dist__calc__pb2.SumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Workload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/middleware.DistributedCalculator/Workload',
            dist__calc__pb2.WorkloadRequest.SerializeToString,
            dist__calc__pb2.WorkloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAverage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/middleware.DistributedCalculator/StreamAverage',
            dist__calc__pb2.Number.SerializeToString,
            dist__calc__pb2.AverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
